<Project>
	<Import Project="version.props" />
	<PropertyGroup>
		<RootNamespace />
		<Authors>lenfon</Authors>
		<Description>A base implementation of strongly typed ids that supports Newtonsoft.Json, System.Text.Json, EntityFramework Core, and Swashbuckle.AspNetCore.</Description>
		<PackageTags>len;id;strongly-typed;primitive;value;DDD</PackageTags>
		<PackageProjectUrl>https://github.com/lenfon/StronglyTypedId</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/lenfon/StronglyTypedId</RepositoryUrl>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<!-- Include symbol files (*.pdb) in the built .nupkg -->
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<None Include="..\..\README.md" Pack="true" PackagePath="\"/>
	</ItemGroup>
</Project>
