namespace Len.StronglyTypedId.Generators;

/// <summary>
/// 为强类型 Id 生成 ASP.NET Core MVC 的模型绑定与路由约束注册入口。
/// </summary>
/// <remarks>
/// <para>
/// 强类型 Id 默认会被 MVC 当作「复杂类型」绑定（尝试按属性名逐个绑定 <c>Value</c>），
/// 路由模板里的 <c>{id}</c> 也拿不到强类型 Id。本生成器通过一条 <c>IModelBinderProvider</c>
/// 让所有实现 <c>IStronglyTypedId&lt;TSelf, TPrimitiveId&gt;</c> 的类型走「字符串 → 静态
/// <c>IParsable&lt;TSelf&gt;.TryParse</c>」这一条干净路径，并额外把每个 Id 注册为路由约束，
/// 使 <c>{id:OrderId}</c> 这类写法能校验分段格式。
/// </para>
/// <para>
/// 生成物只在引用了 <c>Microsoft.AspNetCore.Mvc.dll</c> 时才产出：MVC 的命名空间与类型
/// 只在该程序集（及其依赖 <c>Microsoft.AspNetCore.Routing</c>）出现在使用者编译引用里时才能解析，
/// 缺此门控会在无关项目里生成无法编译的符号。
/// </para>
/// </remarks>
internal class AspNetCoreMvcCodeGenerator : ICodeGenerator
{
    internal static readonly ICodeGenerator Instance = new AspNetCoreMvcCodeGenerator();

    public int Order { get; } = 7;

    public void Generate(
        ImmutableArray<StronglyTypedIdInfo> stronglyTypedIdInfos,
        ImmutableArray<ModuleInfo> modules,
        SourceProductionContext context,
        string version)
    {
        var stronglyTypedIds = StronglyTypedIdDiscovery.Discover(stronglyTypedIdInfos, modules).ToList();

        // 每个 Id 注册为路由约束：路由模板里写 {id:OrderId} 即可按该 Id 的解析规则校验分段格式。
        // 同名简单名（不同命名空间）会按字典覆盖，取最后注册者——属极边缘冲突，沿用门控消歧哲学不予展开。
        var constraintRegistrations = stronglyTypedIds
            .Select(idInfo => $$"""        options.ConstraintMap["{{idInfo.Name}}"] = typeof(global::Len.StronglyTypedId.StronglyTypedIds.StronglyTypedIdRouteConstraint<{{idInfo.FullyQualifiedName}}>);""");

        var code = $$"""
            // <auto-generated />

            namespace Len.StronglyTypedId;

            #nullable enable

            internal static partial class StronglyTypedIds
            {
                /// <summary>
                /// Employ strongly typed IDs in ASP.NET Core MVC model binding.
                /// </summary>
                /// <param name="options"><see cref="global::Microsoft.AspNetCore.Mvc.MvcOptions"/>.</param>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(AspNetCoreMvcCodeGenerator)}}", "{{version}}")]
                public static void ApplyTo(global::Microsoft.AspNetCore.Mvc.MvcOptions options)
                {
                    options.ModelBinderProviders.Insert(0, new StronglyTypedIdModelBinderProvider());
                }

                /// <summary>
                /// Employ strongly typed IDs as ASP.NET Core route constraints.
                /// </summary>
                /// <param name="options"><see cref="global::Microsoft.AspNetCore.Routing.RouteOptions"/>.</param>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(AspNetCoreMvcCodeGenerator)}}", "{{version}}")]
                public static void ApplyTo(global::Microsoft.AspNetCore.Routing.RouteOptions options)
                {
            {{string.Join("\r\n", constraintRegistrations)}}
                }

                /// <summary>
                /// 把「实现了 <see cref="global::Len.StronglyTypedId.IStronglyTypedId{TSelf, TPrimitiveId}"/> 的强类型 Id」路由到
                /// <see cref="StronglyTypedIdModelBinder{TSelf}"/>；其余类型交还 MVC 默认绑定链路。
                /// </summary>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(AspNetCoreMvcCodeGenerator)}}", "{{version}}")]
                private sealed class StronglyTypedIdModelBinderProvider : global::Microsoft.AspNetCore.Mvc.ModelBinding.IModelBinderProvider
                {
                    /// <inheritdoc/>
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(AspNetCoreMvcCodeGenerator)}}", "{{version}}")]
                    public global::Microsoft.AspNetCore.Mvc.ModelBinding.IModelBinder? GetBinder(
                        global::Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderProviderContext context)
                    {
                        var modelType = context.Metadata.ModelType;

                        // 仅当类型实现了 IStronglyTypedId<,> 才接管，避免误伤任何其它可解析类型。
                        // 检查只发生在绑定时的一次性类型判定上，绑定过程本身不再有反射开销。
                        foreach (var interfaceType in modelType.GetInterfaces())
                        {
                            if (interfaceType.IsGenericType
                                && interfaceType.GetGenericTypeDefinition() == typeof(global::Len.StronglyTypedId.IStronglyTypedId<,>))
                            {
                                var binderType = typeof(global::Len.StronglyTypedId.StronglyTypedIds.StronglyTypedIdModelBinder<>).MakeGenericType(modelType);

                                return (global::Microsoft.AspNetCore.Mvc.ModelBinding.IModelBinder)global::System.Activator.CreateInstance(binderType)!;
                            }
                        }

                        return null;
                    }
                }

                /// <summary>
                /// 通用强类型 Id 模型绑定器：以静态 <see cref="global::System.IParsable{TSelf}.TryParse(string?, IFormatProvider?, out TSelf)"/>
                /// 把字符串值还原为强类型 Id（每个强类型 Id 都经 <c>IStronglyTypedId&lt;TSelf, TPrimitiveId&gt;</c> 间接实现 <see cref="global::System.IParsable{TSelf}"/>）。
                /// </summary>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(AspNetCoreMvcCodeGenerator)}}", "{{version}}")]
                private sealed class StronglyTypedIdModelBinder<TId> : global::Microsoft.AspNetCore.Mvc.ModelBinding.IModelBinder where TId : global::System.IParsable<TId>
                {
                    /// <inheritdoc/>
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(AspNetCoreMvcCodeGenerator)}}", "{{version}}")]
                    public global::System.Threading.Tasks.Task BindModelAsync(
                        global::Microsoft.AspNetCore.Mvc.ModelBinding.ModelBindingContext bindingContext)
                    {
                        var valueProviderResult = bindingContext.ValueProvider.GetValue(bindingContext.ModelName);

                        if (valueProviderResult == global::Microsoft.AspNetCore.Mvc.ModelBinding.ValueProviderResult.None)
                        {
                            return global::System.Threading.Tasks.Task.CompletedTask;
                        }

                        var value = valueProviderResult.FirstValue;

                        if (global::System.String.IsNullOrEmpty(value))
                        {
                            return global::System.Threading.Tasks.Task.CompletedTask;
                        }

                        if (TId.TryParse(value, global::System.Globalization.CultureInfo.InvariantCulture, out var id))
                        {
                            bindingContext.Result = global::Microsoft.AspNetCore.Mvc.ModelBinding.ModelBindingResult.Success(id);
                        }
                        else
                        {
                            bindingContext.ModelState.TryAddModelError(
                                bindingContext.ModelName,
                                global::System.String.Concat("The value '", value, "' is not a valid strongly typed id."));
                        }

                        return global::System.Threading.Tasks.Task.CompletedTask;
                    }
                }

                /// <summary>
                /// 通用强类型 Id 路由约束：分段值能经 <see cref="global::System.IParsable{TSelf}.TryParse(string?, IFormatProvider?, out TSelf)"/>
                /// 还原即视为通过，使 <c>{id:OrderId}</c> 这类模板命中强类型 Id 的解析规则。
                /// </summary>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(AspNetCoreMvcCodeGenerator)}}", "{{version}}")]
                private sealed class StronglyTypedIdRouteConstraint<TId> : global::Microsoft.AspNetCore.Routing.IRouteConstraint where TId : global::System.IParsable<TId>
                {
                    /// <inheritdoc/>
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(AspNetCoreMvcCodeGenerator)}}", "{{version}}")]
                    public bool Match(
                        global::Microsoft.AspNetCore.Http.HttpContext? httpContext,
                        global::Microsoft.AspNetCore.Routing.IRouter? route,
                        string routeKey,
                        global::Microsoft.AspNetCore.Routing.RouteValueDictionary values,
                        global::Microsoft.AspNetCore.Routing.RouteDirection routeDirection)
                    {
                        if (!values.TryGetValue(routeKey, out var rawValue) || rawValue is not string text)
                        {
                            return false;
                        }

                        return TId.TryParse(text, global::System.Globalization.CultureInfo.InvariantCulture, out _);
                    }
                }
            }
            """;

        context.AddSource("StronglyTypedIds.AspNetCoreMvc.g.cs", code);
    }
}
