using System.Text;

namespace Len.StronglyTypedId.Generators;

/// <summary>
/// 为强类型 Id 生成 Dapper 的 <c>SqlMapper.TypeHandler&lt;TId&gt;</c> 与统一注册入口。
/// </summary>
/// <remarks>
/// Dapper 默认把未知类型整体序列化为 JSON（按 <c>object</c> 处理），强类型 Id 会退化成一段 JSON 字符串
/// 存进数据库，既读不通也破坏强类型语义。实现 <c>TypeHandler&lt;TId&gt;</c> 后，DbParameter 写入基元值、
/// 读取时还原为强类型 Id，与 EF Core / JSON 的行为保持一致。
/// </remarks>
internal class DapperCodeGenerator : ICodeGenerator
{
    internal static readonly ICodeGenerator Instance = new DapperCodeGenerator();

    public int Order { get; } = 5;

    public void Generate(
        ImmutableArray<StronglyTypedIdInfo> stronglyTypedIdInfos,
        ImmutableArray<ModuleInfo> modules,
        SourceProductionContext context,
        string version)
    {
        var stronglyTypedIds = StronglyTypedIdDiscovery.Discover(stronglyTypedIdInfos, modules).ToList();

        var ambiguousNames = stronglyTypedIds
            .GroupBy(idInfo => idInfo.Name, StringComparer.Ordinal)
            .Where(group => group.Count() > 1)
            .Select(group => group.Key)
            .ToImmutableHashSet(StringComparer.Ordinal);

        var registrations = new StringBuilder();

        foreach (var idInfo in stronglyTypedIds)
        {
            var handlerName = GetHandlerName(idInfo, ambiguousNames.Contains(idInfo.Name));

            // 值类型 Id 的 SetValue 取 .Value 还原基元；引用类型 Id 的 T? 即 T 本身（可空标注），直接取 value。
            // 两条形态都先把 null 映射到 DBNull，使数据库 NULL 与「无 Id」语义对应。
            var setValueBody = idInfo.TypeKindSuffix is null
                ? "parameter.Value = value is null ? (object)global::System.DBNull.Value : value;"
                : "parameter.Value = value is null ? (object)global::System.DBNull.Value : value.Value;";

            var handlerCode = $$"""
                // <auto-generated />

                namespace Len.StronglyTypedId;

                #nullable enable

                internal static partial class StronglyTypedIds
                {
                    /// <inheritdoc/>
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(DapperCodeGenerator)}}", "{{version}}")]
                    class {{handlerName}} : global::Dapper.SqlMapper.TypeHandler<{{idInfo.FullyQualifiedName}}>
                    {
                        /// <inheritdoc/>
                        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(DapperCodeGenerator)}}", "{{version}}")]
                        public override void SetValue(global::System.Data.IDbDataParameter parameter, {{idInfo.FullyQualifiedName}}? value) =>
                            {{setValueBody}}

                        /// <inheritdoc/>
                        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(DapperCodeGenerator)}}", "{{version}}")]
                        public override {{idInfo.FullyQualifiedName}}? Parse(object value) =>
                            value is global::System.DBNull ? default : {{idInfo.FullyQualifiedName}}.Create(({{idInfo.PrimitiveIdTypeName}})value);
                    }
                }
                """;

            context.AddSource($"{idInfo.FullName}.Dapper.g.cs", handlerCode);

            registrations.Append($"\r\n\t\tglobal::Dapper.SqlMapper.AddTypeHandler<{idInfo.FullyQualifiedName}>(new {handlerName}());");
        }

        var registrationCode = $$"""
            // <auto-generated />

            namespace Len.StronglyTypedId;

            #nullable enable

            internal static partial class StronglyTypedIds
            {
                /// <summary>
                /// Employ strongly typed IDs in Dapper.
                /// </summary>
                /// <param name="connection">The Dapper connection to register the type handlers against.</param>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(DapperCodeGenerator)}}", "{{version}}")]
                public static void ApplyTo(global::Dapper.IDbConnection connection)
                {{{registrations}}
                }
            }
            """;

        context.AddSource("StronglyTypedIds.Dapper.g.cs", registrationCode);
    }

    /// <summary>
    /// 取类型处理器的类名，消歧规则与 EF Core 转换器一致。
    /// </summary>
    private static string GetHandlerName(StronglyTypedIdInfo idInfo, bool requiresNamespaceQualifier)
        => requiresNamespaceQualifier
            ? $"{idInfo.FullName.Replace('.', '_')}TypeHandler"
            : $"{idInfo.Name}TypeHandler";
}
