using System.Text;

namespace Len.StronglyTypedId.Generators;

/// <summary>
/// 为强类型 Id 生成 Entity Framework Core 的 <c>ValueConverter</c> 与统一注册入口。
/// </summary>
internal class EfCoreCodeGenerator : ICodeGenerator
{
    internal static readonly ICodeGenerator Instance = new EfCoreCodeGenerator();

    public int Order { get; } = 3;

    public void Generate(
        ImmutableArray<StronglyTypedIdInfo> stronglyTypedIdInfos,
        ImmutableArray<ModuleInfo> modules,
        SourceProductionContext context,
        string version)
    {
        var stronglyTypedIds = StronglyTypedIdDiscovery.Discover(stronglyTypedIdInfos, modules).ToList();

        // 不同命名空间下的同名强类型 Id 都会生成进同一个 StronglyTypedIds 类：转换器若只取短名，
        // 二者就相互冲突（CS0102）。仅在确实出现同名时才用「命名空间_类型名」消歧，以免改动
        // 无冲突场景下既有的转换器类名（使用者可能直接引用该类型）。
        var ambiguousNames = stronglyTypedIds
            .GroupBy(idInfo => idInfo.Name, StringComparer.Ordinal)
            .Where(group => group.Count() > 1)
            .Select(group => group.Key)
            .ToImmutableHashSet(StringComparer.Ordinal);

        var registrations = new StringBuilder();

        foreach (var idInfo in stronglyTypedIds)
        {
            var converterName = GetConverterName(idInfo, ambiguousNames.Contains(idInfo.Name));

            var converterCode = $$"""
                // <auto-generated />

                namespace Len.StronglyTypedId;

                #nullable enable

                internal static partial class StronglyTypedIds
                {
                    /// <inheritdoc/>
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(EfCoreCodeGenerator)}}", "{{version}}")]
                    class {{converterName}} : global::Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<{{idInfo.FullyQualifiedName}}, {{idInfo.PrimitiveIdTypeName}}>
                    {
                        /// <summary>
                        /// Default constructor.
                        /// </summary>
                        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(EfCoreCodeGenerator)}}", "{{version}}")]
                        public {{converterName}}() : base(v => v.Value, val => new {{idInfo.FullyQualifiedName}}(val))
                        {
                        }

                        /// <summary>
                        /// Apply the {{idInfo.Name}} converter to the EntityFramework Core.
                        /// </summary>
                        /// <param name="configurationBuilder"><see cref="global::Microsoft.EntityFrameworkCore.ModelConfigurationBuilder"/></param>
                        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(EfCoreCodeGenerator)}}", "{{version}}")]
                        public static void ApplyTo(global::Microsoft.EntityFrameworkCore.ModelConfigurationBuilder configurationBuilder) =>
                            configurationBuilder.Properties<{{idInfo.FullyQualifiedName}}>().HaveConversion(typeof({{converterName}}));
                    }
                }
                """;

            context.AddSource($"{idInfo.FullName}.EntityFrameworkCore.g.cs", converterCode);

            registrations.Append($"\r\n\t\t{converterName}.ApplyTo(configurationBuilder);");
        }

        var registrationCode = $$"""
            // <auto-generated />

            namespace Len.StronglyTypedId;

            #nullable enable

            internal static partial class StronglyTypedIds
            {
                /// <summary>
                /// Employ strongly typed IDs in Entity Framework Core.
                /// </summary>
                /// <param name="configurationBuilder"><see cref="global::Microsoft.EntityFrameworkCore.ModelConfigurationBuilder"/></param>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(EfCoreCodeGenerator)}}", "{{version}}")]
                public static void ApplyTo(global::Microsoft.EntityFrameworkCore.ModelConfigurationBuilder configurationBuilder)
                {{{registrations}}
                }
            }
            """;

        context.AddSource("StronglyTypedIds.EntityFrameworkCore.g.cs", registrationCode);
    }

    /// <summary>
    /// 取转换器的类名。
    /// </summary>
    /// <param name="idInfo">强类型 Id 描述。</param>
    /// <param name="requiresNamespaceQualifier">
    /// 是否存在位于其它命名空间的同名强类型 Id，需要以命名空间前缀消歧。
    /// </param>
    /// <remarks>
    /// 冲突时使用「命名空间_类型名」（<c>Domain.OrderId</c> → <c>Domain_OrderIdConverter</c>）：
    /// 结果只由该 Id 自身决定，与同一次编译里是否恰好还有别的 Id 无关。
    /// </remarks>
    private static string GetConverterName(StronglyTypedIdInfo idInfo, bool requiresNamespaceQualifier)
        => requiresNamespaceQualifier
            ? $"{idInfo.Namespace.Replace('.', '_')}_{idInfo.Name}Converter"
            : $"{idInfo.Name}Converter";
}
