using System.Text;

namespace Len.StronglyTypedId.Generators;

/// <summary>
/// 为强类型 Id 生成 Entity Framework Core 的 <c>ValueConverter</c> 与统一注册入口。
/// </summary>
internal class EfCoreCodeGenerator : ICodeGenerator
{
    internal static readonly ICodeGenerator Instance = new EfCoreCodeGenerator();

    public int Order { get; } = 3;

    public void Generate(
        ImmutableArray<StronglyTypedIdInfo> stronglyTypedIdInfos,
        ImmutableArray<ModuleInfo> modules,
        SourceProductionContext context,
        string version)
    {
        var registrations = new StringBuilder();

        foreach (var idInfo in StronglyTypedIdDiscovery.Discover(stronglyTypedIdInfos, modules))
        {
            var converterCode = $$"""
                // <auto-generated />

                namespace Len.StronglyTypedId;

                #nullable enable

                internal static partial class StronglyTypedIds
                {
                    /// <inheritdoc/>
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(EfCoreCodeGenerator)}}", "{{version}}")]
                    class {{idInfo.Name}}Converter : global::Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<{{idInfo.FullyQualifiedName}}, {{idInfo.PrimitiveIdTypeName}}>
                    {
                        /// <summary>
                        /// Default constructor.
                        /// </summary>
                        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(EfCoreCodeGenerator)}}", "{{version}}")]
                        public {{idInfo.Name}}Converter() : base(v => v.Value, val => new {{idInfo.FullyQualifiedName}}(val))
                        {
                        }

                        /// <summary>
                        /// Apply the {{idInfo.Name}} converter to the EntityFramework Core.
                        /// </summary>
                        /// <param name="configurationBuilder"><see cref="global::Microsoft.EntityFrameworkCore.ModelConfigurationBuilder"/></param>
                        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(EfCoreCodeGenerator)}}", "{{version}}")]
                        public static void ApplyTo(global::Microsoft.EntityFrameworkCore.ModelConfigurationBuilder configurationBuilder) =>
                            configurationBuilder.Properties<{{idInfo.FullyQualifiedName}}>().HaveConversion(typeof({{idInfo.Name}}Converter));
                    }
                }
                """;

            context.AddSource($"{idInfo.FullName}.EntityFrameworkCore.g.cs", converterCode);

            registrations.Append($"\r\n\t\t{idInfo.Name}Converter.ApplyTo(configurationBuilder);");
        }

        var registrationCode = $$"""
            // <auto-generated />

            namespace Len.StronglyTypedId;

            #nullable enable

            internal static partial class StronglyTypedIds
            {
                /// <summary>
                /// Employ strongly typed IDs in Entity Framework Core.
                /// </summary>
                /// <param name="configurationBuilder"><see cref="global::Microsoft.EntityFrameworkCore.ModelConfigurationBuilder"/></param>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(EfCoreCodeGenerator)}}", "{{version}}")]
                public static void ApplyTo(global::Microsoft.EntityFrameworkCore.ModelConfigurationBuilder configurationBuilder)
                {{{registrations}}
                }
            }
            """;

        context.AddSource("StronglyTypedIds.EntityFrameworkCore.g.cs", registrationCode);
    }
}
