namespace Len.StronglyTypedId.Generators;

/// <summary>
/// 为强类型 Id 生成 Newtonsoft.Json 转换器。
/// </summary>
internal class NewtonsoftJsonCodeGenerator : ICodeGenerator
{
    internal static readonly ICodeGenerator Instance = new NewtonsoftJsonCodeGenerator();

    public int Order { get; } = 2;

    public void Generate(
        ImmutableArray<StronglyTypedIdInfo> stronglyTypedIdInfos,
        ImmutableArray<ModuleInfo> modules,
        SourceProductionContext context,
        string version)
    {
        foreach (var idInfo in stronglyTypedIdInfos)
        {
            var header = $$"""
                // <auto-generated />
                
                namespace {{idInfo.Namespace}};
                
                #nullable enable
                """ + "\n\n";

            var declaration = $$"""
                [global::Newtonsoft.Json.JsonConverter(typeof(NewtonsoftJsonConverter))]
                partial record{{idInfo.TypeKindSuffix}} {{idInfo.Name}}
                {
                    /// <inheritdoc/>
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(NewtonsoftJsonCodeGenerator)}}", "{{version}}")]
                    class NewtonsoftJsonConverter : global::Newtonsoft.Json.JsonConverter<{{idInfo.Name}}?>
                    {
                        /// <inheritdoc/>
                        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(NewtonsoftJsonCodeGenerator)}}", "{{version}}")]
                        public override {{idInfo.Name}}? ReadJson(
                            global::Newtonsoft.Json.JsonReader reader,
                            global::System.Type objectType,
                            {{idInfo.Name}}? existingValue,
                            bool hasExistingValue,
                            global::Newtonsoft.Json.JsonSerializer serializer) =>
                            serializer.Deserialize<{{idInfo.PrimitiveIdTypeName}}?>(reader) switch
                            {
                                { } value => {{idInfo.Name}}.Create(value),
                                null when (objectType.IsClass || global::System.Nullable.GetUnderlyingType(objectType) is not null) => null,
                                _ => throw new global::System.InvalidOperationException($"Cannot get the value of a token type '{reader.TokenType}' as a {{idInfo.Name}}")
                            };
                
                        /// <inheritdoc/>
                        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(NewtonsoftJsonCodeGenerator)}}", "{{version}}")]
                        public override void WriteJson(
                            global::Newtonsoft.Json.JsonWriter writer,
                            {{idInfo.Name}}? value,
                            global::Newtonsoft.Json.JsonSerializer serializer)
                        {
                            if (value is { Value: var primitiveId })
                            {
                                writer.WriteValue(primitiveId);
                            }
                            else
                            {
                                writer.WriteNull();
                            }
                        }
                    }
                }
                """;

            var code = header + GeneratedCode.NestInContainingTypes(idInfo, declaration);

            // 与另外两个内嵌式生成器一致地统一行尾：嵌套包装是按 \n 逐行拼出来的，
            // 与原始字符串字面量（跟随源文件行尾）相接会得到混排行尾。非嵌套时本调用是空操作，
            // 因为整段文本来自同一个字面量、行尾本就一致。
            context.AddSource($"{idInfo.FullName}.NewtonsoftJson.g.cs", GeneratedCode.NormalizeLineEndings(code));
        }
    }
}
