namespace Len.StronglyTypedId.Generators;

/// <summary>
/// 生成强类型 Id 的核心实现：<c>IStronglyTypedId&lt;TSelf, TPrimitiveId&gt;</c>、<c>IParsable&lt;TSelf&gt;</c>
/// 与相等性运算符。
/// </summary>
internal class StronglyTypedIdCodeGenerator : ICodeGenerator
{
    internal static readonly ICodeGenerator Instance = new StronglyTypedIdCodeGenerator();

    public int Order { get; } = 0;

    public void Generate(
        ImmutableArray<StronglyTypedIdInfo> stronglyTypedIdInfos,
        ImmutableArray<ModuleInfo> modules,
        SourceProductionContext context,
        string version)
    {
        foreach (var idInfo in stronglyTypedIdInfos)
        {
            var code = $$"""
                // <auto-generated />

                namespace {{idInfo.Namespace}};

                #nullable enable

                partial record{{idInfo.TypeKindSuffix}} {{idInfo.Name}} :
                    global::Len.StronglyTypedId.IStronglyTypedId<{{idInfo.Name}}, {{idInfo.PrimitiveIdTypeName}}>,
                    global::System.IParsable<{{idInfo.Name}}>,
                    global::System.Numerics.IEqualityOperators<{{idInfo.Name}}, {{idInfo.Name}}, bool>
                {
                    public static {{idInfo.Name}} Create({{idInfo.PrimitiveIdTypeName}} value) => new {{idInfo.Name}}(value);

                    /// <inheritdoc/>
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(StronglyTypedIdCodeGenerator)}}", "{{version}}")]
                    public static {{idInfo.Name}} Parse(string value, global::System.IFormatProvider? provider)
                    {
                        if (!TryParse(value, provider, out var id))
                        {
                            throw new global::System.ArgumentException("Could not parse supplied value.", nameof(value));
                        }

                        return id;
                    }

                    /// <inheritdoc/>
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(StronglyTypedIdCodeGenerator)}}", "{{version}}")]
                    public static bool TryParse(
                        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] string? value,
                        global::System.IFormatProvider? provider,
                        [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out {{idInfo.Name}} result)
                    {
                        if ({{(idInfo.PrimitiveIdTypeName == "string" ? "value is { Length: > 0 } val" : $"{idInfo.PrimitiveIdTypeName}.TryParse(value, provider, out var val)")}})
                        {
                            result = new {{idInfo.Name}}(val);
                            return true;
                        }

                        result = default;
                        return false;
                    }
                }
                """;

            context.AddSource($"{idInfo.FullName}.g.cs", code);
        }
    }
}
