namespace Len.StronglyTypedId.Generators;

/// <summary>
/// 为强类型 Id 生成 System.Text.Json 转换器。
/// </summary>
internal class SystemTextJsonCodeGenerator : ICodeGenerator
{
    internal static readonly ICodeGenerator Instance = new SystemTextJsonCodeGenerator();

    public int Order { get; } = 1;

    public void Generate(
        ImmutableArray<StronglyTypedIdInfo> stronglyTypedIdInfos,
        ImmutableArray<ModuleInfo> modules,
        SourceProductionContext context,
        string version)
    {
        foreach (var idInfo in stronglyTypedIdInfos)
        {
            var code = $$"""
                // <auto-generated />
                
                namespace {{idInfo.Namespace}};
                
                #nullable enable
                
                [global::System.Text.Json.Serialization.JsonConverter(typeof(SystemTextJsonConverter))]
                partial record{{idInfo.TypeKindSuffix}} {{idInfo.Name}}
                {
                    /// <inheritdoc/>
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(SystemTextJsonCodeGenerator)}}", "{{version}}")]
                    class SystemTextJsonConverter : global::System.Text.Json.Serialization.JsonConverter<{{idInfo.Name}}>
                    {
                        /// <inheritdoc/>
                        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(SystemTextJsonCodeGenerator)}}", "{{version}}")]
                        public override {{idInfo.Name}} Read(
                            ref global::System.Text.Json.Utf8JsonReader reader, 
                            global::System.Type typeToConvert, 
                            global::System.Text.Json.JsonSerializerOptions options) =>
                            global::System.Text.Json.JsonSerializer.Deserialize<{{idInfo.PrimitiveIdTypeName}}?>(ref reader, options) switch
                            {
                                { } value => new {{idInfo.Name}}(value),
                                _ => throw new global::System.InvalidOperationException($"Cannot get the value of a token type '{reader.TokenType}' as a {{idInfo.Name}}")
                            };
                
                        /// <inheritdoc/>
                        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(SystemTextJsonCodeGenerator)}}", "{{version}}")]
                        public override void Write(
                            global::System.Text.Json.Utf8JsonWriter writer, 
                            {{idInfo.Name}} value, 
                            global::System.Text.Json.JsonSerializerOptions options)
                        {
                            if (value is { Value: var primitiveId })
                            {
                                global::System.Text.Json.JsonSerializer.Serialize(writer, primitiveId, options);
                            }
                            else
                            {
                                writer.WriteNullValue();
                            }
                        }
                    }
                }
                """;

            context.AddSource($"{idInfo.FullName}.SystemTextJson.g.cs", code);
        }
    }
}
