//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   一个强类型的资源类，用于查找本地化的字符串等。
/// </summary>
// 此类是由 StronglyTypedResourceBuilder
// 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
// 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
// (以 /str 作为命令选项)，或重新生成 VS 项目。
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }
    
    /// <summary>
    ///   返回此类使用的缓存的 ResourceManager 实例。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources", typeof(Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   重写当前线程的 CurrentUICulture 属性，对
    ///   使用此强类型资源类的所有资源查找执行重写。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   查找类似 The parameter &apos;{0}&apos; must not be nullable. 的本地化字符串。
    /// </summary>
    internal static string ParameterCannotBeNullableMessage {
        get {
            return ResourceManager.GetString("ParameterCannotBeNullableMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Parameter must not be nullable 的本地化字符串。
    /// </summary>
    internal static string ParameterCannotBeNullableTitle {
        get {
            return ResourceManager.GetString("ParameterCannotBeNullableTitle", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 The parameter name should be ‘Value’. 的本地化字符串。
    /// </summary>
    internal static string ParameterNameMustBeValueMessage {
        get {
            return ResourceManager.GetString("ParameterNameMustBeValueMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Parameter name should be ‘Value’. 的本地化字符串。
    /// </summary>
    internal static string ParameterNameMustBeValueTitle {
        get {
            return ResourceManager.GetString("ParameterNameMustBeValueTitle", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 The parameter type must be one of the following: Guid, String, byte, short, int, long, sbyte, ushort, uint, or ulong. 的本地化字符串。
    /// </summary>
    internal static string ParameterTypeIsInvalidMessage {
        get {
            return ResourceManager.GetString("ParameterTypeIsInvalidMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Parameter type is not valid 的本地化字符串。
    /// </summary>
    internal static string ParameterTypeIsInvalidTitle {
        get {
            return ResourceManager.GetString("ParameterTypeIsInvalidTitle", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 The type &apos;{0}&apos; cannot be declared abstract. 的本地化字符串。
    /// </summary>
    internal static string TypeCannotBeAbstractMessage {
        get {
            return ResourceManager.GetString("TypeCannotBeAbstractMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Type cannot be declared abstract 的本地化字符串。
    /// </summary>
    internal static string TypeCannotBeAbstractTitle {
        get {
            return ResourceManager.GetString("TypeCannotBeAbstractTitle", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 The type &apos;{0}&apos; cannot be declared as generic. 的本地化字符串。
    /// </summary>
    internal static string TypeCannotBeGenericMessage {
        get {
            return ResourceManager.GetString("TypeCannotBeGenericMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Type cannot be declared as generic 的本地化字符串。
    /// </summary>
    internal static string TypeCannotBeGenericTitle {
        get {
            return ResourceManager.GetString("TypeCannotBeGenericTitle", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 The type &apos;{0}&apos; cannot be nested and must have a namespace. 的本地化字符串。
    /// </summary>
    internal static string TypeCannotBeNestedAndMustHaveNamespaceMessage {
        get {
            return ResourceManager.GetString("TypeCannotBeNestedAndMustHaveNamespaceMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Type cannot be nested and must have a namespace 的本地化字符串。
    /// </summary>
    internal static string TypeCannotBeNestedAndMustHaveNamespaceTitle {
        get {
            return ResourceManager.GetString("TypeCannotBeNestedAndMustHaveNamespaceTitle", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 The type &apos;{0}&apos; must be defined as partial. 的本地化字符串。
    /// </summary>
    internal static string TypeMustBePartialMessage {
        get {
            return ResourceManager.GetString("TypeMustBePartialMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Type must be defined as partial 的本地化字符串。
    /// </summary>
    internal static string TypeMustBePartialTitle {
        get {
            return ResourceManager.GetString("TypeMustBePartialTitle", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 The type &apos;{0}&apos; must be defined as a record. 的本地化字符串。
    /// </summary>
    internal static string TypeMustBeRecordMessage {
        get {
            return ResourceManager.GetString("TypeMustBeRecordMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Type must be defined as a record 的本地化字符串。
    /// </summary>
    internal static string TypeMustBeRecordTitle {
        get {
            return ResourceManager.GetString("TypeMustBeRecordTitle", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 The type &apos;{0}&apos; must have a primary constructor with exactly one parameter. 的本地化字符串。
    /// </summary>
    internal static string TypeMustHavePrimaryConstructorWithExactlyHaveOneParameterMessage {
        get {
            return ResourceManager.GetString("TypeMustHavePrimaryConstructorWithExactlyHaveOneParameterMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Type must have a primary constructor with exactly one parameter 的本地化字符串。
    /// </summary>
    internal static string TypeMustHavePrimaryConstructorWithExactlyHaveOneParameterTitle {
        get {
            return ResourceManager.GetString("TypeMustHavePrimaryConstructorWithExactlyHaveOneParameterTitle", resourceCulture);
        }
    }
}
