using FluentAssertions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Testing;
using System.Reflection;

namespace Len.StronglyTypedId.Generators;

public class StronglyTypedIdGeneratorTests
{
    /// <summary>
    /// 生成代码里 <c>GeneratedCodeAttribute</c> 的版本号。
    /// </summary>
    /// <remarks>
    /// 生成器写进产物的版本取自<b>自身程序集</b>的版本（见 <c>StronglyTypedIdGenerator._version</c>），
    /// 而该版本由根 <c>version.props</c> 决定。因此期望快照必须按同一来源取值 ——
    /// 写死字面量会让整套快照在每次改版本号（也就是每次发版）时集体失效。
    /// </remarks>
    private static readonly string GeneratorVersion = typeof(StronglyTypedIdGenerator).Assembly.GetName().Version!.ToString(3);

    [Theory]
    [InlineData("record")]
    [InlineData("record struct")]
    public void Generator_Should_ReturnGeneratedCode_WhenCorrectSourceCode(string record)
    {
        var code = $""""
            using System;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial {record} OrderId(Guid Value);
            """";
        List<string> expectedCodes = GetExpectedCodes(record);

        // Act
        var actualCodes = GetGeneratedCode(code);

        // Assert
        var verifier = new DefaultVerifier();

        actualCodes
            .Should()
            .SatisfyRespectively(
                first => verifier.EqualOrDiff(expectedCodes[0], first),
                second => verifier.EqualOrDiff(expectedCodes[1], second),
                third => verifier.EqualOrDiff(expectedCodes[2], third)
            );
    }

    private static List<string> GetExpectedCodes(string record = "record")
    {
        // record 与 record struct 的产物只差两处：record 关键字后的 struct 后缀，
        // 以及 IComparable<TSelf>.CompareTo 的形参 —— 无约束泛型里的 T? 对值类型即 T 本身，
        // 引用类型写可空、值类型不写才与接口签名一致（否则 CS8767）。
        var compareToParameter = record == "record" ? "OrderId? other" : "OrderId other";
        var compareToBody = record == "record"
            ? "other is null ? 1 : Value.CompareTo(other.Value)"
            : "Value.CompareTo(other.Value)";

        return [

            $$"""
            // <auto-generated />
            
            namespace Len.StronglyTypedId;
            
            #nullable enable
            
            partial {{record}} OrderId :
                global::Len.StronglyTypedId.IStronglyTypedId<OrderId, global::System.Guid>,
                global::System.IParsable<OrderId>,
                global::System.ISpanParsable<OrderId>,
                global::System.IComparable<OrderId>,
                global::System.Numerics.IEqualityOperators<OrderId, OrderId, bool>,
                global::System.Numerics.IComparisonOperators<OrderId, OrderId, bool>,
                global::System.IFormattable,
                global::System.ISpanFormattable
            {
                /// <inheritdoc/>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("StronglyTypedIdCodeGenerator", "{{GeneratorVersion}}")]
                public static OrderId Create(global::System.Guid value) => new OrderId(value);
            
                /// <inheritdoc/>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("StronglyTypedIdCodeGenerator", "{{GeneratorVersion}}")]
                public static OrderId Parse(string value, global::System.IFormatProvider? provider)
                {
                    if (!TryParse(value, provider, out var id))
                    {
                        throw new global::System.ArgumentException("Could not parse supplied value.", nameof(value));
                    }
            
                    return id;
                }
            
                /// <inheritdoc/>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("StronglyTypedIdCodeGenerator", "{{GeneratorVersion}}")]
                public static bool TryParse(
                    [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] string? value,
                    global::System.IFormatProvider? provider,
                    [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out OrderId result)
                {
                    if (global::System.Guid.TryParse(value, provider, out var val))
                    {
                        result = new OrderId(val);
                        return true;
                    }
            
                    result = default;
                    return false;
                }
            
                /// <inheritdoc/>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("StronglyTypedIdCodeGenerator", "{{GeneratorVersion}}")]
                public static OrderId Parse(global::System.ReadOnlySpan<char> value, global::System.IFormatProvider? provider)
                {
                    if (!TryParse(value, provider, out var id))
                    {
                        throw new global::System.ArgumentException("Could not parse supplied value.", nameof(value));
                    }
            
                    return id;
                }
            
                /// <inheritdoc/>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("StronglyTypedIdCodeGenerator", "{{GeneratorVersion}}")]
                public static bool TryParse(
                    global::System.ReadOnlySpan<char> value,
                    global::System.IFormatProvider? provider,
                    [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out OrderId result)
                {
                    if (global::System.Guid.TryParse(value, provider, out var val))
                    {
                        result = new OrderId(val);
                        return true;
                    }
            
                    result = default;
                    return false;
                }
            
                /// <inheritdoc/>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("StronglyTypedIdCodeGenerator", "{{GeneratorVersion}}")]
                public int CompareTo({{compareToParameter}}) => {{compareToBody}};
            
                /// <inheritdoc/>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("StronglyTypedIdCodeGenerator", "{{GeneratorVersion}}")]
                public static bool operator <(OrderId left, OrderId right) => left.Value.CompareTo(right.Value) < 0;
            
                /// <inheritdoc/>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("StronglyTypedIdCodeGenerator", "{{GeneratorVersion}}")]
                public static bool operator >(OrderId left, OrderId right) => left.Value.CompareTo(right.Value) > 0;
            
                /// <inheritdoc/>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("StronglyTypedIdCodeGenerator", "{{GeneratorVersion}}")]
                public static bool operator <=(OrderId left, OrderId right) => left.Value.CompareTo(right.Value) <= 0;
            
                /// <inheritdoc/>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("StronglyTypedIdCodeGenerator", "{{GeneratorVersion}}")]
                public static bool operator >=(OrderId left, OrderId right) => left.Value.CompareTo(right.Value) >= 0;
            
                /// <inheritdoc/>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("StronglyTypedIdCodeGenerator", "{{GeneratorVersion}}")]
                public override string ToString() => Value.ToString() ?? string.Empty;
            
                /// <inheritdoc/>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("StronglyTypedIdCodeGenerator", "{{GeneratorVersion}}")]
                public string ToString(string? format, global::System.IFormatProvider? formatProvider) =>
                    Value.ToString(format, formatProvider);
            
                /// <inheritdoc/>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("StronglyTypedIdCodeGenerator", "{{GeneratorVersion}}")]
                public bool TryFormat(
                    global::System.Span<char> destination,
                    out int charsWritten,
                    global::System.ReadOnlySpan<char> format,
                    global::System.IFormatProvider? provider) =>
                    ((global::System.ISpanFormattable)Value).TryFormat(destination, out charsWritten, format, provider);
            }
            """,
            $$"""
            // <auto-generated />
            
            namespace Len.StronglyTypedId;
            
            #nullable enable
            
            [global::System.Text.Json.Serialization.JsonConverter(typeof(SystemTextJsonConverter))]
            partial {{record}} OrderId
            {
                /// <inheritdoc/>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SystemTextJsonCodeGenerator", "{{GeneratorVersion}}")]
                class SystemTextJsonConverter : global::System.Text.Json.Serialization.JsonConverter<OrderId>
                {
                    /// <inheritdoc/>
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SystemTextJsonCodeGenerator", "{{GeneratorVersion}}")]
                    public override OrderId Read(
                        ref global::System.Text.Json.Utf8JsonReader reader, 
                        global::System.Type typeToConvert, 
                        global::System.Text.Json.JsonSerializerOptions options) =>
                        global::System.Text.Json.JsonSerializer.Deserialize<global::System.Guid?>(ref reader, options) switch
                        {
                            { } value => OrderId.Create(value),
                            _ => throw new global::System.InvalidOperationException($"Cannot get the value of a token type '{reader.TokenType}' as a OrderId")
                        };
            
                    /// <inheritdoc/>
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SystemTextJsonCodeGenerator", "{{GeneratorVersion}}")]
                    public override void Write(
                        global::System.Text.Json.Utf8JsonWriter writer, 
                        OrderId value, 
                        global::System.Text.Json.JsonSerializerOptions options)
                    {
                        if (value is { Value: var primitiveId })
                        {
                            global::System.Text.Json.JsonSerializer.Serialize(writer, primitiveId, options);
                        }
                        else
                        {
                            writer.WriteNullValue();
                        }
                    }
            
                    /// <inheritdoc/>
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SystemTextJsonCodeGenerator", "{{GeneratorVersion}}")]
                    public override void WriteAsPropertyName(
                        global::System.Text.Json.Utf8JsonWriter writer,
                        OrderId value,
                        global::System.Text.Json.JsonSerializerOptions options)
                    {
                        if (value is { Value: var primitiveId })
                        {
                            writer.WritePropertyName(primitiveId.ToString(null, global::System.Globalization.CultureInfo.InvariantCulture));
                        }
                        else
                        {
                            throw new global::System.NotSupportedException($"A null OrderId cannot be written as a JSON property name.");
                        }
                    }
            
                    /// <inheritdoc/>
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SystemTextJsonCodeGenerator", "{{GeneratorVersion}}")]
                    public override OrderId ReadAsPropertyName(
                        ref global::System.Text.Json.Utf8JsonReader reader,
                        global::System.Type typeToConvert,
                        global::System.Text.Json.JsonSerializerOptions options)
                    {
                        var propertyName = reader.GetString();
            
                        if (OrderId.TryParse(propertyName, global::System.Globalization.CultureInfo.InvariantCulture, out var id))
                        {
                            return id;
                        }
            
                        throw new global::System.Text.Json.JsonException($"Cannot convert the JSON property name '{propertyName}' to a OrderId.");
                    }
                }
            }
            """,
            $$"""
            // <auto-generated />
            
            namespace Len.StronglyTypedId;
            
            #nullable enable
            
            [global::Newtonsoft.Json.JsonConverter(typeof(NewtonsoftJsonConverter))]
            partial {{record}} OrderId
            {
                /// <inheritdoc/>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NewtonsoftJsonCodeGenerator", "{{GeneratorVersion}}")]
                class NewtonsoftJsonConverter : global::Newtonsoft.Json.JsonConverter<OrderId?>
                {
                    /// <inheritdoc/>
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NewtonsoftJsonCodeGenerator", "{{GeneratorVersion}}")]
                    public override OrderId? ReadJson(
                        global::Newtonsoft.Json.JsonReader reader,
                        global::System.Type objectType,
                        OrderId? existingValue,
                        bool hasExistingValue,
                        global::Newtonsoft.Json.JsonSerializer serializer) =>
                        serializer.Deserialize<global::System.Guid?>(reader) switch
                        {
                            { } value => OrderId.Create(value),
                            null when (objectType.IsClass || global::System.Nullable.GetUnderlyingType(objectType) is not null) => null,
                            _ => throw new global::System.InvalidOperationException($"Cannot get the value of a token type '{reader.TokenType}' as a OrderId")
                        };
            
                    /// <inheritdoc/>
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NewtonsoftJsonCodeGenerator", "{{GeneratorVersion}}")]
                    public override void WriteJson(
                        global::Newtonsoft.Json.JsonWriter writer,
                        OrderId? value,
                        global::Newtonsoft.Json.JsonSerializer serializer)
                    {
                        if (value is { Value: var primitiveId })
                        {
                            writer.WriteValue(primitiveId);
                        }
                        else
                        {
                            writer.WriteNull();
                        }
                    }
                }
            }
            """,
        ];
    }

    [Fact]
    public void Generator_Should_ReturnEmpty_WhenNotPartial()
    {
        var code = """"
            using System;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public record OrderId(Guid Value);
            """";

        GetGeneratedCode(code).Should().BeEmpty();
    }

    [Fact]
    public void Generator_Should_ReturnEmpty_WhenConstructorNoArguments()
    {
        var code = """"
            using System;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial record OrderId();
            """";

        GetGeneratedCode(code).Should().BeEmpty();
    }

    [Fact]
    public void Generator_Should_ReturnEmpty_WhenNotRecord()
    {
        var code = """"
            using System;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial class OrderId{}
            """";

        GetGeneratedCode(code).Should().BeEmpty();
    }

    [Fact]
    public void Generator_Should_ReturnEmpty_WhenAbstractRecord()
    {
        var code = """"
            using System;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public abstract partial record OrderId(Guid Value);
            """";

        GetGeneratedCode(code).Should().BeEmpty();
    }

    [Fact]
    public void Generator_Should_ReturnEmpty_WhenArgumentsIsNullable()
    {
        var code = """"
            using System;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial record OrderId(Guid? Value);
            """";

        GetGeneratedCode(code).Should().BeEmpty();
    }

    [Fact]
    public void Generator_Should_ReturnEmpty_WhenNotSupportedType()
    {
        var code = """"
            using System;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial record OrderId(bool Value);
            """";

        GetGeneratedCode(code).Should().BeEmpty();
    }

    /// <summary>
    /// 回归用例：与 BCL 基元同名、却不在 <c>System</c> 命名空间下的类型不是基元类型，生成器不得产出代码。
    /// </summary>
    /// <remarks>
    /// 判据曾只比简单名，于是 <c>Probe.Fake.Guid</c> 被当成 <see cref="System.Guid"/> 写进生成代码，
    /// 使用者拿到的是报在生成文件里的 CS0315。
    /// </remarks>
    [Fact]
    public void Generator_Should_ReturnEmpty_WhenPrimitiveTypeSharesSimpleNameWithBclType()
    {
        var code = """
            using System;

            namespace Probe.Fake
            {
                public struct Guid
                {
                }
            }

            namespace Len.StronglyTypedId
            {
                [StronglyTypedId]
                public partial record struct OrderId(Probe.Fake.Guid Value);
            }
            """;

        GetGeneratedCode(code).Should().BeEmpty();
    }

    /// <summary>
    /// 回归用例：<c>[StronglyTypedId]</c> 标在不承载主构造函数的那一段上时，仍必须产出代码。
    /// </summary>
    /// <remarks>
    /// 生成器的语法谓词只对「带 attribute 的那一段」被调用。若它要求该段自身形如 <c>(Value)</c>，
    /// 这种把主构造函数写在另一段的分段写法就会既没有任何产物、也不报任何诊断 ——
    /// 而分析器是按「类型」判定的，同样不会报错，于是问题彻底静默。
    /// </remarks>
    [Fact]
    public void Generator_Should_GenerateCode_WhenAttributeIsOnSegmentWithoutPrimaryConstructor()
    {
        var code = """
            using System;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial record struct OrderId;

            public partial record struct OrderId(Guid Value);
            """;

        var actualCodes = GetGeneratedCode(code);

        actualCodes.Should().NotBeEmpty();
        actualCodes.Should().Contain(c => c!.Contains("global::Len.StronglyTypedId.IStronglyTypedId<OrderId, global::System.Guid>"));
        actualCodes.Should().Contain(c => c!.Contains("public static OrderId Create(global::System.Guid value)"));
    }

    [Fact]
    public void Generator_Should_ReturnEmpty_WhenArgumentNameIsOther()
    {
        var code = """"
            using System;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial record OrderId(Guid value);
            """";

        GetGeneratedCode(code).Should().BeEmpty();
    }

    [Fact]
    public void Generator_Should_ReturnEmpty_WhenNotNamespace()
    {
        var code = """"
            using System;

            [StronglyTypedId]
            public partial record OrderId(Guid Value);
            """";

        GetGeneratedCode(code).Should().BeEmpty();
    }

    [Theory]
    [InlineData("record struct", "string")]
    [InlineData("record", "int")]
    [InlineData("record struct", "int")]
    [InlineData("record struct", "byte")]
    [InlineData("record", "sbyte")]
    [InlineData("record struct", "short")]
    [InlineData("record", "ushort")]
    [InlineData("record struct", "uint")]
    [InlineData("record", "long")]
    [InlineData("record struct", "ulong")]
    public void Generator_Should_GenerateCode_ForNonGuidPrimitive(string record, string primitive)
    {
        var code = $""""
            using System;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial {record} OrderId({primitive} Value);
            """";

        var actualCodes = GetGeneratedCode(code);

        // 生成器对 string / int 等非 Guid 基元同样应输出代码
        actualCodes.Should().NotBeEmpty();
        actualCodes.Should().Contain(c => c!.Contains("global::System.IParsable<OrderId>"));
        actualCodes.Should().Contain(c => c!.Contains("public static OrderId Create"));
        actualCodes.Should().Contain(c => c!.Contains($"Create({primitive} value)"));
    }

    /// <summary>
    /// 构造被测合成编译：先按 <see cref="ShouldReferenceAssembly"/> 过滤 AppDomain 中已加载的程序集，
    /// 再并上默认种子程序集与调用方通过 <paramref name="extraAssemblyTypes"/> 显式指定的程序集。
    /// </summary>
    private static CSharpCompilation CreateDefaultCompilation(string sourceCode, params Type[] extraAssemblyTypes)
        => CreateCompilation(sourceCode, extraAssemblyTypes, []);

    /// <summary>
    /// 同 <see cref="CreateDefaultCompilation(string, Type[])"/>，但额外接受任意 <see cref="MetadataReference"/>，
    /// 用于构造「引用程序集里已有生成产物」这类多程序集消费者画像。
    /// </summary>
    /// <remarks>
    /// 项目引用（<c>CompilationReference</c>）无法用 <see cref="Type"/> 表达，只能以引用实例传入。
    /// </remarks>
    private static CSharpCompilation CreateCompilation(
        string sourceCode,
        Type[] extraAssemblyTypes,
        MetadataReference[] extraReferences)
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(sourceCode);

        var assemblies = new[]
        {
            typeof(StronglyTypedIdAttribute).Assembly,
            typeof(System.Text.Json.JsonSerializer).Assembly,
            typeof(Newtonsoft.Json.JsonSerializer).Assembly
        };

        // ShouldReferenceAssembly 只过滤来自 AppDomain 的程序集（防止 TestBase / EF Core / Swagger 等
        // 程序集因被其它测试加载而污染发现结果）。通过 extraAssemblyTypes 显式注入的程序集不在此列，
        // 必须原样保留，否则 EF Core / Swagger 生成器将检测不到对应模块而不生成代码。
        var references = AppDomain.CurrentDomain
            .GetAssemblies()
            .Union(assemblies)
            .Distinct()
            .Where(assembly => !assembly.IsDynamic)
            .Where(ShouldReferenceAssembly)
            .Union(extraAssemblyTypes.Select(type => type.Assembly).Where(assembly => !assembly.IsDynamic))
            .Select(assembly => MetadataReference.CreateFromFile(assembly.Location))
            .Cast<MetadataReference>()
            .Concat(extraReferences);

        return CSharpCompilation.Create(
            "Len.StronglyTypedId.Generator.Test",
            [syntaxTree],
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
        );
    }

    private static IEnumerable<string?> GetGeneratedCode(string sourceCode)
    {
        var compilation = CreateDefaultCompilation(sourceCode);

        var generator = new StronglyTypedIdGenerator();

        CSharpGeneratorDriver
            .Create(generator)
            .RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out var diagnostics);

        diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).Should().BeEmpty();

        return outputCompilation.SyntaxTrees.Skip(1).Select(s => s?.ToString());
    }

    /// <summary>
    /// 与 <see cref="GetGeneratedCode"/> 类似，但按 hint 名称返回所有生成的源文件，便于针对单个生成器产物断言。
    /// 额外程序集（EF Core / Swashbuckle 等）通过 <paramref name="extraAssemblyTypes"/> 显式引入，
    /// 避免被 AppDomain 中已加载的其它测试程序集污染，导致 EF Core / Swagger 生成器意外触发。
    /// </summary>
    private static IReadOnlyDictionary<string, string> GetGeneratedCodeByHint(string sourceCode, params Type[] extraAssemblyTypes)
        => GetGeneratedCodeByHint(sourceCode, extraAssemblyTypes, []);

    /// <summary>
    /// 同 <see cref="GetGeneratedCodeByHint(string, Type[])"/>，但额外接受任意 <see cref="MetadataReference"/>。
    /// </summary>
    private static IReadOnlyDictionary<string, string> GetGeneratedCodeByHint(
        string sourceCode,
        Type[] extraAssemblyTypes,
        MetadataReference[] extraReferences)
    {
        var compilation = CreateCompilation(sourceCode, extraAssemblyTypes, extraReferences);

        var generator = new StronglyTypedIdGenerator();

        var result = CSharpGeneratorDriver
            .Create(generator)
            .RunGenerators(compilation)
            .GetRunResult();

        result.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).Should().BeEmpty();

        return result.Results[0].GeneratedSources
            .ToDictionary(g => g.HintName, g => g.SourceText.ToString());
    }

    /// <summary>
    /// 生成器测试不应引用以下程序集，否则会触发 EF Core / Swagger 生成器或被 TestBase 中已实现的强类型 Id 污染发现结果。
    /// 这些程序集仅在对应测试里通过 <see cref="GetGeneratedCodeByHint"/> 的 <paramref name="extraAssemblyTypes"/> 显式引入。
    /// </summary>
    private static bool ShouldReferenceAssembly(Assembly assembly)
        => assembly.GetName().Name is not
            ("Len.StronglyTypedId.TestBase" or "Microsoft.EntityFrameworkCore" or "Swashbuckle.AspNetCore.SwaggerGen" or "Microsoft.OpenApi");

    #region EF Core 生成器（EfCoreCodeGenerator）

    [Theory]
    [InlineData("record struct")]
    [InlineData("record")]
    public void EfCore_Should_GenerateConverter_WhenReferencedAndConfigureConventions(string record)
    {
        var template = """
            using System;
            using Microsoft.EntityFrameworkCore;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial {0} OrderId(Guid Value);

            public class TestDbContext : DbContext
            {{
                protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder) {{ }}
            }}
            """;
        var code = string.Format(template, record);

        var generated = GetGeneratedCodeByHint(code, typeof(Microsoft.EntityFrameworkCore.DbContext));

        generated.Should().ContainKey("Len.StronglyTypedId.OrderId.EntityFrameworkCore.g.cs");
        generated.Should().ContainKey("StronglyTypedIds.EntityFrameworkCore.g.cs");

        var converter = generated["Len.StronglyTypedId.OrderId.EntityFrameworkCore.g.cs"];
        converter.Should().Contain("class OrderIdConverter : global::Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<global::Len.StronglyTypedId.OrderId, global::System.Guid>");
        converter.Should().Contain("configurationBuilder.Properties<global::Len.StronglyTypedId.OrderId>().HaveConversion(typeof(OrderIdConverter));");

        generated["StronglyTypedIds.EntityFrameworkCore.g.cs"]
            .Should().Contain("OrderIdConverter.ApplyTo(configurationBuilder);");
    }

    [Fact]
    public void EfCore_Should_GenerateConverterForIntPrimitive()
    {
        var code = """
            using System;
            using Microsoft.EntityFrameworkCore;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial record struct OrderId(int Value);

            public class TestDbContext : DbContext
            {
                protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder) { }
            }
            """;

        var generated = GetGeneratedCodeByHint(code, typeof(Microsoft.EntityFrameworkCore.DbContext));

        generated["Len.StronglyTypedId.OrderId.EntityFrameworkCore.g.cs"]
            .Should().Contain("ValueConverter<global::Len.StronglyTypedId.OrderId, int>");
    }

    [Fact]
    public void EfCore_Should_NotGenerate_WhenNoConfigureConventions()
    {
        var code = """
            using System;
            using Microsoft.EntityFrameworkCore;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial record struct OrderId(Guid Value);
            """;

        var generated = GetGeneratedCodeByHint(code, typeof(Microsoft.EntityFrameworkCore.DbContext));

        generated.Keys.Should().NotContain(k => k.EndsWith(".EntityFrameworkCore.g.cs"));
    }

    /// <summary>
    /// 回归用例：不同命名空间下的同名强类型 Id 都生成进同一个 <c>StronglyTypedIds</c> 类，
    /// 转换器类名必须区分，否则相互冲突（CS0102 等）。
    /// </summary>
    /// <remarks>
    /// 只有确实出现同名时才给类名加命名空间前缀，无冲突场景下既有的 <c>OrderIdConverter</c>
    /// 命名保持不变（见上方 <c>EfCore_Should_GenerateConverter_WhenReferencedAndConfigureConventions</c>）。
    /// </remarks>
    [Fact]
    public void EfCore_Should_DisambiguateConverterNames_WhenSameNameInDifferentNamespaces()
    {
        var code = """
            using Len.StronglyTypedId;
            using Microsoft.EntityFrameworkCore;

            namespace Domain
            {
                [StronglyTypedId]
                public partial record struct OrderId(System.Guid Value);
            }

            namespace Contracts
            {
                [StronglyTypedId]
                public partial record struct OrderId(System.Guid Value);
            }

            namespace Host
            {
                public class TestDbContext : DbContext
                {
                    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder) { }
                }
            }
            """;

        var generated = GetGeneratedCodeByHint(code, typeof(Microsoft.EntityFrameworkCore.DbContext));

        generated["Domain.OrderId.EntityFrameworkCore.g.cs"]
            .Should().Contain("class Domain_OrderIdConverter :")
            .And.Contain("HaveConversion(typeof(Domain_OrderIdConverter))");

        generated["Contracts.OrderId.EntityFrameworkCore.g.cs"]
            .Should().Contain("class Contracts_OrderIdConverter :")
            .And.Contain("HaveConversion(typeof(Contracts_OrderIdConverter))");

        generated["StronglyTypedIds.EntityFrameworkCore.g.cs"]
            .Should().Contain("Domain_OrderIdConverter.ApplyTo(configurationBuilder);")
            .And.Contain("Contracts_OrderIdConverter.ApplyTo(configurationBuilder);");
    }

    #endregion

    #region Swagger 生成器（SwaggerCodeGenerator）

    [Theory]
    [InlineData("record struct")]
    [InlineData("record")]
    public void Swagger_Should_GenerateMapType_ForGuid(string record)
    {
        var code = $""""
            using System;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial {record} OrderId(Guid Value);
            """";

        var generated = GetGeneratedCodeByHint(code, typeof(Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions));

        generated.Should().ContainKey("StronglyTypedIds.Swagger.g.cs");
        generated["StronglyTypedIds.Swagger.g.cs"]
            .Should().Contain("options.MapType<global::Len.StronglyTypedId.OrderId>(() => new global::Microsoft.OpenApi.Models.OpenApiSchema { Type = \"string\", Format = \"uuid\" });");
    }

    [Fact]
    public void Swagger_Should_GenerateMapType_ForInt()
    {
        var code = """
            using System;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial record struct OrderId(int Value);
            """;

        var generated = GetGeneratedCodeByHint(code, typeof(Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions));

        generated["StronglyTypedIds.Swagger.g.cs"]
            .Should().Contain("options.MapType<global::Len.StronglyTypedId.OrderId>(() => new global::Microsoft.OpenApi.Models.OpenApiSchema { Type = \"integer\", Format = \"int32\" });");
    }

    [Fact]
    public void Swagger_Should_NotGenerate_WhenSwashbuckleNotReferenced()
    {
        var code = """
            using System;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial record struct OrderId(Guid Value);
            """;

        var generated = GetGeneratedCodeByHint(code);

        generated.Keys.Should().NotContain("StronglyTypedIds.Swagger.g.cs");
    }

    #endregion

    #region 生成产物的可编译性（消费者未开启 ImplicitUsings）

    /// <summary>
    /// 回归用例：全部生成产物在「<c>ImplicitUsings=disable</c> 的消费者」里必须能编译。
    /// </summary>
    /// <remarks>
    /// <para>
    /// using 指令的作用域是文件级：合成编译的源码里虽有 <c>using System;</c>，但生成出来的每个文件
    /// 都得自带（或用全限定名写明）它依赖的每一个类型。这与
    /// <c>&lt;ImplicitUsings&gt;disable&lt;/ImplicitUsings&gt;</c>（且非 Web SDK）的消费者等价。
    /// </para>
    /// <para>
    /// 曾如此暴露过 Newtonsoft 产物里的裸 <c>Nullable</c>（<c>System.Nullable</c> 的短名）：开启
    /// ImplicitUsings 的消费者因为隐式 <c>global using System;</c> 而侥幸通过，关闭后即 CS0103。
    /// 断言放在此处而非某个具体生成器的测试里，是因为它守护的是全部生成器共有的契约。
    /// </para>
    /// </remarks>
    [Fact]
    public void GeneratedCode_Should_Compile_WithoutImplicitUsings()
    {
        var code = """
            using System;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial record OrderId(Guid Value);
            """;

        var compilation = CreateDefaultCompilation(code);

        // 显式传入取消令牌：生成 + Emit 是本套件里最重的两步，xUnit1051 要求的正是这个。
        var cancellationToken = TestContext.Current.CancellationToken;

        CSharpGeneratorDriver
            .Create(new StronglyTypedIdGenerator())
            .RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out _, cancellationToken);

        using var stream = new MemoryStream();
        var emit = outputCompilation.Emit(stream, cancellationToken: cancellationToken);

        var errors = emit.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).ToArray();

        errors.Should().BeEmpty(string.Join("\n", errors.Select(error => error.ToString())));
    }

    #endregion

    #region 生成器侧能力断言：校验、字典键、比较与格式化

    /// <summary>
    /// 指定 <c>Validator</c> 时，<c>Create</c> 以内联条件表达式拒绝非法值。
    /// </summary>
    /// <remarks>
    /// 断言的是「校验确实接在 <c>Create</c> 与两个 <c>TryParse</c> 重载上」这一形态，而不是某个实现细节：
    /// 三者是使用者可能用到的全部构造入口，漏掉任何一个都会让非法值从对应路径溜进 Id。
    /// </remarks>
    [Fact]
    public void Generator_Should_EmitValidationGuard_WhenValidatorIsConfigured()
    {
        var code = """
            using System;

            namespace Len.StronglyTypedId;

            [StronglyTypedId(Validator = nameof(Validate))]
            public partial record struct OrderId(Guid Value)
            {
                private static bool Validate(Guid value) => value != Guid.Empty;
            }
            """;

        var generated = GetGeneratedCodeByHint(code);

        generated["Len.StronglyTypedId.OrderId.g.cs"]
            .Should().Contain("public static OrderId Create(global::System.Guid value) => Validate(value) ? new OrderId(value) : throw new global::System.ArgumentException($\"The value '{value}' is not a valid OrderId.\", nameof(value));")
            .And.Contain("if (global::System.Guid.TryParse(value, provider, out var val) && Validate(val))");
    }

    /// <summary>
    /// 未指定 <c>Validator</c> 时产物里不应出现任何校验痕迹 —— 无验证器的形态必须与加入该能力之前逐字符一致。
    /// </summary>
    [Fact]
    public void Generator_Should_NotEmitValidationGuard_WhenValidatorIsAbsent()
    {
        var generated = GetGeneratedCodeByHint(IdSource);

        generated["Len.StronglyTypedId.OrderId.g.cs"]
            .Should().Contain("public static OrderId Create(global::System.Guid value) => new OrderId(value);")
            .And.NotContain("Validate(");
    }

    /// <summary>
    /// 字符串基元的 span 重载以 <c>value.ToString()</c> 派生校验参数，属校验参数来源的另一条分支。
    /// </summary>
    [Fact]
    public void Generator_Should_PassSpanDerivedValue_ToValidatorForStringPrimitive()
    {
        var code = """
            using System;

            namespace Len.StronglyTypedId;

            [StronglyTypedId(Validator = nameof(Validate))]
            public partial record struct OrderId(string Value)
            {
                private static bool Validate(string value) => value.Length <= 8;
            }
            """;

        var generated = GetGeneratedCodeByHint(code);

        generated["Len.StronglyTypedId.OrderId.g.cs"]
            .Should().Contain("if (value is { Length: > 0 } && Validate(value))")
            .And.Contain("if (value.Length > 0 && Validate(value.ToString()))");
    }

    /// <summary>
    /// System.Text.Json 的字典键走 <c>ReadAsPropertyName</c> / <c>WriteAsPropertyName</c>，
    /// 两者都必须生成，否则 <c>Dictionary&lt;OrderId, TValue&gt;</c> 在运行期直接抛 <c>NotSupportedException</c>。
    /// </summary>
    /// <remarks>
    /// 写键一律取不变文化下的文本形式：<c>string</c> 基元的属性名就是取值本身，其余基元经
    /// <c>ToString(null, InvariantCulture)</c>，避免键名随当前区域性漂移。
    /// </remarks>
    [Theory]
    [InlineData("Guid", "primitiveId.ToString(null, global::System.Globalization.CultureInfo.InvariantCulture)")]
    [InlineData("int", "primitiveId.ToString(null, global::System.Globalization.CultureInfo.InvariantCulture)")]
    [InlineData("string", "primitiveId")]
    public void SystemTextJson_Should_EmitDictionaryKeyAccessors(string primitive, string writeExpression)
    {
        var converter = GetGeneratedCodeByHint(OrderIdSource(primitive))["Len.StronglyTypedId.OrderId.SystemTextJson.g.cs"];

        converter.Should()
            .Contain("public override void WriteAsPropertyName(")
            .And.Contain($"writer.WritePropertyName({writeExpression});")
            .And.Contain("public override OrderId ReadAsPropertyName(");
    }

    /// <summary>
    /// <c>string</c> 基元的属性名直接构造，不经解析。
    /// </summary>
    [Fact]
    public void SystemTextJson_Should_CreateDirectly_WhenReadingStringPropertyName()
    {
        var converter = GetGeneratedCodeByHint(OrderIdSource("string"))["Len.StronglyTypedId.OrderId.SystemTextJson.g.cs"];

        converter.Should().Contain("return OrderId.Create(reader.GetString()!);");
    }

    /// <summary>
    /// 其余基元的属性名按不变文化解析，解析失败抛 <c>JsonException</c>。
    /// </summary>
    /// <remarks>
    /// 此处不能转调 <c>Read</c>：方法名路径上 <c>TokenType</c> 是 <c>PropertyName</c> 而非 <c>String</c>，
    /// 内层转换器会失败。
    /// </remarks>
    [Fact]
    public void SystemTextJson_Should_ParsePropertyName_WithInvariantCulture()
    {
        var converter = GetGeneratedCodeByHint(OrderIdSource("Guid"))["Len.StronglyTypedId.OrderId.SystemTextJson.g.cs"];

        converter.Should()
            .Contain("var propertyName = reader.GetString();")
            .And.Contain("if (OrderId.TryParse(propertyName, global::System.Globalization.CultureInfo.InvariantCulture, out var id))")
            .And.Contain("throw new global::System.Text.Json.JsonException($\"Cannot convert the JSON property name '{propertyName}' to a OrderId.\");");
    }

    /// <summary>
    /// 比较、span 解析与格式化成员按基元能力条件生成。
    /// </summary>
    [Theory]
    [InlineData("Guid")]
    [InlineData("int")]
    public void Generator_Should_EmitComparisonAndFormattingCapabilities(string primitive)
    {
        var generated = GetGeneratedCodeByHint(OrderIdSource(primitive))["Len.StronglyTypedId.OrderId.g.cs"];

        generated.Should()
            .Contain("global::System.IComparable<OrderId>")
            .And.Contain("global::System.Numerics.IComparisonOperators<OrderId, OrderId, bool>")
            .And.Contain("global::System.ISpanParsable<OrderId>")
            .And.Contain("global::System.IFormattable")
            .And.Contain("global::System.ISpanFormattable")
            .And.Contain("public override string ToString() => Value.ToString() ?? string.Empty;")
            .And.Contain("((global::System.ISpanFormattable)Value).TryFormat(destination, out charsWritten, format, provider);");
    }

    /// <summary>
    /// <c>string</c> 未实现 <c>IFormattable</c> / <c>ISpanFormattable</c>，因此 string 基元的 Id 也不实现它们。
    /// </summary>
    /// <remarks>
    /// 这两个接口若照抄到所有基元上，消费者代码能编译但运行期语义是错的（<c>Value.ToString(format, provider)</c> 对
    /// <c>string</c> 不存在）—— 实际后果是生成文件根本编译不过，属运行时之前就会暴露的一类。
    /// </remarks>
    [Fact]
    public void Generator_Should_OmitFormattingInterfaces_ForStringPrimitive()
    {
        var generated = GetGeneratedCodeByHint(OrderIdSource("string"))["Len.StronglyTypedId.OrderId.g.cs"];

        generated.Should()
            .NotContain("IFormattable")
            .And.NotContain("TryFormat")
            .And.Contain("public override string ToString() => Value.ToString() ?? string.Empty;");
    }

    /// <summary>
    /// 全部生成器同时启用、且消费者的编译引用只含必要程序集时，产物必须能做到「零警告」Emit。
    /// </summary>
    /// <remarks>
    /// <para>
    /// 上一个用例只断言「无错误」。生成器产物里的可疑签名（例如少一个可空标注、接口实现与声明不一致）
    /// 往往只产生警告，消费者若开了 <c>TreatWarningsAsErrors</c> 就会在下载包之后才发现。
    /// </para>
    /// <para>
    /// 断言取 <c>Severity &gt;= Warning</c> 而非仅 <c>Warning</c>：错误也一并拦下，无需分开两次检查。
    /// 程序集统一性告警（CS1701/CS1702）来自合成编译拼装引用程序集的方式，与被测产物无关，故排除。
    /// </para>
    /// </remarks>
    [Fact]
    public void GeneratedCode_Should_EmitWithoutWarnings_WhenEveryGeneratorIsEnabled()
    {
        var code = """
            using System;
            using Microsoft.EntityFrameworkCore;

            namespace Len.StronglyTypedId;

            [StronglyTypedId(Validator = nameof(Validate))]
            public partial record struct OrderId(Guid Value)
            {
                private static bool Validate(Guid value) => value != Guid.Empty;
            }

            public class TestDbContext : DbContext
            {
                protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder) { }
            }
            """;

        var compilation = CreateCompilation(
            code,
            [typeof(Microsoft.EntityFrameworkCore.DbContext), typeof(Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions)],
            [
                MetadataReference.CreateFromFile(typeof(Microsoft.OpenApi.Models.OpenApiSchema).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(Microsoft.Extensions.DependencyInjection.IServiceCollection).Assembly.Location),
            ]);

        var cancellationToken = TestContext.Current.CancellationToken;

        CSharpGeneratorDriver
            .Create(new StronglyTypedIdGenerator())
            .RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out _, cancellationToken);

        using var stream = new MemoryStream();
        var emit = outputCompilation.Emit(stream, cancellationToken: cancellationToken);

        var diagnostics = emit.Diagnostics
            .Where(diagnostic => diagnostic.Severity >= DiagnosticSeverity.Warning)
            .Where(diagnostic => diagnostic.Id is not ("CS1701" or "CS1702"))
            .Select(diagnostic => diagnostic.ToString())
            .ToArray();

        diagnostics.Should().BeEmpty(string.Join("\n", diagnostics));
    }

    /// <summary>
    /// 按基元类型构造单 Id 的消费者源码。
    /// </summary>
    private static string OrderIdSource(string primitive)
    {
        var source = $$"""
            using System;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial record struct OrderId({{primitive}} Value);
            """;

        return source;
    }

    #endregion

    #region 消费者画像：多程序集 / 多段 partial / 全部生成器同时启用

    /// <summary>
    /// 引用程序集里已由生成器补齐接口的强类型 Id，必须与本次编译声明的 Id 一起被纳入 EF Core 转换器。
    /// </summary>
    /// <remarks>
    /// 两类 Id 走的是不同发现路径：本次声明的由 <c>ForAttributeWithMetadataName</c> 直接提供，
    /// 引用程序集里的则要靠 <see cref="StronglyTypedIdDiscovery"/> 枚举模块类型。只有把两者合并进
    /// 同一份注册文件，跨程序集使用强类型 Id 才开箱可用。
    /// </remarks>
    [Fact]
    public void EfCore_Should_IncludeConverters_ForIdsDeclaredInReferencedAssembly()
    {
        var generated = GetGeneratedCodeByHint(
            DbContextSource,
            [typeof(Microsoft.EntityFrameworkCore.DbContext)],
            [CreateReferencedDomainReference()]);

        generated.Should().ContainKey("Referenced.Domain.LegacyId.EntityFrameworkCore.g.cs");
        generated.Should().ContainKey("Len.StronglyTypedId.OrderId.EntityFrameworkCore.g.cs");
        generated["StronglyTypedIds.EntityFrameworkCore.g.cs"]
            .Should().Contain("LegacyIdConverter.ApplyTo(configurationBuilder);")
            .And.Contain("OrderIdConverter.ApplyTo(configurationBuilder);");
    }

    /// <summary>
    /// Swagger 侧同理：引用程序集里已生成的强类型 Id 也要注册 <c>MapType</c>。
    /// </summary>
    [Fact]
    public void Swagger_Should_IncludeMapType_ForIdsDeclaredInReferencedAssembly()
    {
        var generated = GetGeneratedCodeByHint(
            IdSource,
            [typeof(Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions), typeof(Microsoft.Extensions.DependencyInjection.IServiceCollection)],
            [
                MetadataReference.CreateFromFile(typeof(Microsoft.OpenApi.Models.OpenApiSchema).Assembly.Location),
                CreateReferencedDomainReference(),
            ]);

        generated["StronglyTypedIds.Swagger.g.cs"]
            .Should().Contain("options.MapType<global::Referenced.Domain.LegacyId>(")
            .And.Contain("options.MapType<global::Len.StronglyTypedId.OrderId>(");
    }

    /// <summary>
    /// 强类型 Id 跨多个 partial 声明段拆分时，同一类型仍只应产出一份生成文件。
    /// </summary>
    /// <remarks>
    /// 生成器的语法谓词只匹配带主构造函数的那一段，但类型符号是唯一的，因此
    /// 无论声明了几段，产物数量都必须与单段声明一致。
    /// </remarks>
    [Theory]
    [InlineData("record struct")]
    [InlineData("record")]
    public void Generator_Should_GenerateSingleSetOfFiles_ForSegmentedPartialDeclaration(string record)
    {
        var code = $$"""
            using System;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial {{record}} OrderId(Guid Value);

            public partial {{record}} OrderId
            {
                public bool IsEmpty => Value == Guid.Empty;
            }

            public partial {{record}} OrderId
            {
                public Guid Unwrap() => Value;
            }
            """;

        var generated = GetGeneratedCodeByHint(code);

        generated.Keys.Should().BeEquivalentTo(
        [
            "Len.StronglyTypedId.OrderId.g.cs",
            "Len.StronglyTypedId.OrderId.SystemTextJson.g.cs",
            "Len.StronglyTypedId.OrderId.NewtonsoftJson.g.cs",
        ]);
    }

    /// <summary>
    /// 全部生成器同时启用时，所有产物必须能在同一编译里一起通过 Emit。
    /// </summary>
    /// <remarks>
    /// 逐个生成器单独测只能发现各自的问题，产物之间还会相互作用：EF Core 与 Swagger 都把
    /// <c>StronglyTypedIds</c> 写成 <c>partial</c> 类并要求合并到同一命名空间，核心生成器又在同一命名空间下
    /// 声明 Id 类型。本用例把「同一编译里同时出现全部产物」这一真实场景整体编译一遍。
    /// </remarks>
    [Fact]
    public void GeneratedCode_Should_Compile_WhenEveryGeneratorIsEnabled()
    {
        var code = """
            using System;
            using System;
            using Microsoft.EntityFrameworkCore;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial record struct OrderId(Guid Value);

            public class TestDbContext : DbContext
            {
                protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder) { }
            }
            """;

        var compilation = CreateCompilation(
            code,
            [typeof(Microsoft.EntityFrameworkCore.DbContext), typeof(Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions)],
            [
                MetadataReference.CreateFromFile(typeof(Microsoft.OpenApi.Models.OpenApiSchema).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(Microsoft.Extensions.DependencyInjection.IServiceCollection).Assembly.Location),
            ]);

        var cancellationToken = TestContext.Current.CancellationToken;

        CSharpGeneratorDriver
            .Create(new StronglyTypedIdGenerator())
            .RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out _, cancellationToken);

        using var stream = new MemoryStream();
        var emit = outputCompilation.Emit(stream, cancellationToken: cancellationToken);

        var errors = emit.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).ToArray();

        errors.Should().BeEmpty(string.Join("\n", errors.Select(error => error.ToString())));
    }

    #region 消费者画像测试源码

    private const string IdSource = """
        using System;

        namespace Len.StronglyTypedId;

        [StronglyTypedId]
        public partial record struct OrderId(Guid Value);
        """;

    private const string DbContextSource = """
        using System;
        using Microsoft.EntityFrameworkCore;

        namespace Len.StronglyTypedId;

        [StronglyTypedId]
        public partial record struct OrderId(Guid Value);

        public class TestDbContext : DbContext
        {
            protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder) { }
        }
        """;

    /// <summary>
    /// 等价于使用者引用的另一个已编译项目：其中的强类型 Id 已由生成器补齐接口实现。
    /// </summary>
    private const string ReferencedDomainSource = """
        namespace Referenced.Domain;

        public readonly record struct LegacyId(global::System.Guid Value)
            : global::Len.StronglyTypedId.IStronglyTypedId<LegacyId, global::System.Guid>
        {
            public static LegacyId Create(global::System.Guid value) => new(value);

            public static LegacyId Parse(string value, global::System.IFormatProvider? provider)
                => new(global::System.Guid.Parse(value, provider));

            public static bool TryParse(
                string? value,
                global::System.IFormatProvider? provider,
                out LegacyId result)
            {
                if (global::System.Guid.TryParse(value, provider, out var primitiveId))
                {
                    result = new LegacyId(primitiveId);
                    return true;
                }

                result = default;
                return false;
            }
        }
        """;

    /// <summary>
    /// 把 <see cref="ReferencedDomainSource"/> 编译成一个项目引用（<c>CompilationReference</c>）。
    /// </summary>
    private static MetadataReference CreateReferencedDomainReference()
    {
        var compilation = CSharpCompilation.Create(
            "ReferencedDomain",
            [CSharpSyntaxTree.ParseText(ReferencedDomainSource)],
            [
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(StronglyTypedIdAttribute).Assembly.Location),
            ],
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        return compilation.ToMetadataReference();
    }

    #endregion

    #endregion
}
