using FluentAssertions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Testing;
using System.Reflection;

namespace Len.StronglyTypedId.Generators;

public class StronglyTypedIdGeneratorTests
{
    [Theory]
    [InlineData("record")]
    [InlineData("record struct")]
    public void Generator_Should_ReturnGeneratedCode_WhenCorrectSourceCode(string record)
    {
        var code = $""""
            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial {record} OrderId(Guid Value);
            """";
        List<string> expectedCodes = GetExpectedCodes(record);

        // Act
        var actualCodes = GetGeneratedCode(code);

        // Assert
        var verifier = new DefaultVerifier();

        actualCodes
            .Should()
            .SatisfyRespectively(
                first => verifier.EqualOrDiff(expectedCodes[0], first),
                second => verifier.EqualOrDiff(expectedCodes[1], second),
                third => verifier.EqualOrDiff(expectedCodes[2], third)
            );
    }

    private static List<string> GetExpectedCodes(string record = "record")
    {
        return [
            $$"""
            // <auto-generated />
            
            namespace Len.StronglyTypedId;
            
            #nullable enable
            
            partial {{record}} OrderId :
                global::Len.StronglyTypedId.IStronglyTypedId<OrderId, Guid>,
                global::System.IParsable<OrderId>,
                global::System.Numerics.IEqualityOperators<OrderId, OrderId, bool>
            {
                public static OrderId Create(Guid value) => new OrderId(value);
            
                /// <inheritdoc/>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("StronglyTypedIdCodeGenerator", "1.0.0")]
                public static OrderId Parse(string value, global::System.IFormatProvider? provider)
                {
                    if (!TryParse(value, provider, out var id))
                    {
                        throw new global::System.ArgumentException("Could not parse supplied value.", nameof(value));
                    }
            
                    return id;
                }
            
                /// <inheritdoc/>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("StronglyTypedIdCodeGenerator", "1.0.0")]
                public static bool TryParse(
                    [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] string? value,
                    global::System.IFormatProvider? provider,
                    [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out OrderId result)
                {
                    if (Guid.TryParse(value, provider, out var val))
                    {
                        result = new OrderId(val);
                        return true;
                    }
            
                    result = default;
                    return false;
                }
            }
            """,
            $$"""
            // <auto-generated />
            
            namespace Len.StronglyTypedId;
            
            #nullable enable
            
            [global::System.Text.Json.Serialization.JsonConverter(typeof(SystemTextJsonConverter))]
            partial {{record}} OrderId
            {
                /// <inheritdoc/>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SystemTextJsonCodeGenerator", "1.0.0")]
                class SystemTextJsonConverter : global::System.Text.Json.Serialization.JsonConverter<OrderId>
                {
                    /// <inheritdoc/>
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SystemTextJsonCodeGenerator", "1.0.0")]
                    public override OrderId Read(
                        ref global::System.Text.Json.Utf8JsonReader reader, 
                        global::System.Type typeToConvert, 
                        global::System.Text.Json.JsonSerializerOptions options) =>
                        global::System.Text.Json.JsonSerializer.Deserialize<Guid?>(ref reader, options) switch
                        {
                            { } value => new OrderId(value),
                            _ => throw new global::System.InvalidOperationException($"Cannot get the value of a token type '{reader.TokenType}' as a OrderId")
                        };
            
                    /// <inheritdoc/>
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SystemTextJsonCodeGenerator", "1.0.0")]
                    public override void Write(
                        global::System.Text.Json.Utf8JsonWriter writer, 
                        OrderId value, 
                        global::System.Text.Json.JsonSerializerOptions options)
                    {
                        if (value is { Value: var primitiveId })
                        {
                            global::System.Text.Json.JsonSerializer.Serialize(writer, primitiveId, options);
                        }
                        else
                        {
                            writer.WriteNullValue();
                        }
                    }
                }
            }
            """,
            $$""""
            // <auto-generated />

            namespace Len.StronglyTypedId;

            #nullable enable

            [global::Newtonsoft.Json.JsonConverter(typeof(NewtonsoftJsonConverter))]
            partial {{record}} OrderId
            {
                /// <inheritdoc/>
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NewtonsoftJsonCodeGenerator", "1.0.0")]
                class NewtonsoftJsonConverter : global::Newtonsoft.Json.JsonConverter<OrderId?>
                {
                    /// <inheritdoc/>
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NewtonsoftJsonCodeGenerator", "1.0.0")]
                    public override OrderId? ReadJson(
                        global::Newtonsoft.Json.JsonReader reader,
                        global::System.Type objectType,
                        OrderId? existingValue,
                        bool hasExistingValue,
                        global::Newtonsoft.Json.JsonSerializer serializer) =>
                        serializer.Deserialize<Guid?>(reader) switch
                        {
                            { } value => new OrderId(value),
                            null when (objectType.IsClass || global::System.Nullable.GetUnderlyingType(objectType) is not null) => null,
                            _ => throw new global::System.InvalidOperationException($"Cannot get the value of a token type '{reader.TokenType}' as a OrderId")
                        };

                    /// <inheritdoc/>
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NewtonsoftJsonCodeGenerator", "1.0.0")]
                    public override void WriteJson(
                        global::Newtonsoft.Json.JsonWriter writer,
                        OrderId? value,
                        global::Newtonsoft.Json.JsonSerializer serializer)
                    {
                        if (value is { Value: var primitiveId })
                        {
                            writer.WriteValue(primitiveId);
                        }
                        else
                        {
                            writer.WriteNull();
                        }
                    }
                }
            }
            """"
        ];
    }

    [Fact]
    public void Generator_Should_ReturnEmpty_WhenNotPartial()
    {
        var code = """"
            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public record OrderId(Guid Value);
            """";

        GetGeneratedCode(code).Should().BeEmpty();
    }

    [Fact]
    public void Generator_Should_ReturnEmpty_WhenConstructorNoArguments()
    {
        var code = """"
            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial record OrderId();
            """";

        GetGeneratedCode(code).Should().BeEmpty();
    }

    [Fact]
    public void Generator_Should_ReturnEmpty_WhenNotRecord()
    {
        var code = """"
            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial class OrderId{}
            """";

        GetGeneratedCode(code).Should().BeEmpty();
    }

    [Fact]
    public void Generator_Should_ReturnEmpty_WhenAbstractRecord()
    {
        var code = """"
            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public abstract partial record OrderId(Guid Value);
            """";

        GetGeneratedCode(code).Should().BeEmpty();
    }

    [Fact]
    public void Generator_Should_ReturnEmpty_WhenArgumentsIsNullable()
    {
        var code = """"
            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial record OrderId(Guid? Value);
            """";

        GetGeneratedCode(code).Should().BeEmpty();
    }

    [Fact]
    public void Generator_Should_ReturnEmpty_WhenNotSupportedType()
    {
        var code = """"
            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial record OrderId(bool Value);
            """";

        GetGeneratedCode(code).Should().BeEmpty();
    }

    [Fact]
    public void Generator_Should_ReturnEmpty_WhenArgumentNameIsOther()
    {
        var code = """"
            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial record OrderId(Guid value);
            """";

        GetGeneratedCode(code).Should().BeEmpty();
    }

    [Fact]
    public void Generator_Should_ReturnEmpty_WhenNotNamespace()
    {
        var code = """"
            [StronglyTypedId]
            public partial record OrderId(Guid Value);
            """";

        GetGeneratedCode(code).Should().BeEmpty();
    }

    [Theory]
    [InlineData("record struct", "string")]
    [InlineData("record", "int")]
    [InlineData("record struct", "int")]
    [InlineData("record struct", "byte")]
    [InlineData("record", "sbyte")]
    [InlineData("record struct", "short")]
    [InlineData("record", "ushort")]
    [InlineData("record struct", "uint")]
    [InlineData("record", "long")]
    [InlineData("record struct", "ulong")]
    public void Generator_Should_GenerateCode_ForNonGuidPrimitive(string record, string primitive)
    {
        var code = $""""
            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial {record} OrderId({primitive} Value);
            """";

        var actualCodes = GetGeneratedCode(code);

        // 生成器对 string / int 等非 Guid 基元同样应输出代码
        actualCodes.Should().NotBeEmpty();
        actualCodes.Should().Contain(c => c!.Contains("global::System.IParsable<OrderId>"));
        actualCodes.Should().Contain(c => c!.Contains("public static OrderId Create"));
        actualCodes.Should().Contain(c => c!.Contains($"Create({primitive} value)"));
    }

    /// <summary>
    /// 构造被测合成编译：先按 <see cref="ShouldReferenceAssembly"/> 过滤 AppDomain 中已加载的程序集，
    /// 再并上默认种子程序集与调用方通过 <paramref name="extraAssemblyTypes"/> 显式指定的程序集。
    /// </summary>
    private static CSharpCompilation CreateDefaultCompilation(string sourceCode, params Type[] extraAssemblyTypes)
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(sourceCode);

        var assemblies = new[]
        {
            typeof(StronglyTypedIdAttribute).Assembly,
            typeof(System.Text.Json.JsonSerializer).Assembly,
            typeof(Newtonsoft.Json.JsonSerializer).Assembly
        };

        // ShouldReferenceAssembly 只过滤来自 AppDomain 的程序集（防止 TestBase / EF Core / Swagger 等
        // 程序集因被其它测试加载而污染发现结果）。通过 extraAssemblyTypes 显式注入的程序集不在此列，
        // 必须原样保留，否则 EF Core / Swagger 生成器将检测不到对应模块而不生成代码。
        var references = AppDomain.CurrentDomain
            .GetAssemblies()
            .Union(assemblies)
            .Distinct()
            .Where(assembly => !assembly.IsDynamic)
            .Where(ShouldReferenceAssembly)
            .Union(extraAssemblyTypes.Select(type => type.Assembly).Where(assembly => !assembly.IsDynamic))
            .Select(assembly => MetadataReference.CreateFromFile(assembly.Location))
            .Cast<MetadataReference>();

        return CSharpCompilation.Create(
            "Len.StronglyTypedId.Generator.Test",
            [syntaxTree],
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
        );
    }

    private static IEnumerable<string?> GetGeneratedCode(string sourceCode)
    {
        var compilation = CreateDefaultCompilation(sourceCode);

        var generator = new StronglyTypedIdGenerator();

        CSharpGeneratorDriver
            .Create(generator)
            .RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out var diagnostics);

        diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).Should().BeEmpty();

        return outputCompilation.SyntaxTrees.Skip(1).Select(s => s?.ToString());
    }

    /// <summary>
    /// 与 <see cref="GetGeneratedCode"/> 类似，但按 hint 名称返回所有生成的源文件，便于针对单个生成器产物断言。
    /// 额外程序集（EF Core / Swashbuckle 等）通过 <paramref name="extraAssemblyTypes"/> 显式引入，
    /// 避免被 AppDomain 中已加载的其它测试程序集污染，导致 EF Core / Swagger 生成器意外触发。
    /// </summary>
    private static IReadOnlyDictionary<string, string> GetGeneratedCodeByHint(string sourceCode, params Type[] extraAssemblyTypes)
    {
        var compilation = CreateDefaultCompilation(sourceCode, extraAssemblyTypes);

        var generator = new StronglyTypedIdGenerator();

        var result = CSharpGeneratorDriver
            .Create(generator)
            .RunGenerators(compilation)
            .GetRunResult();

        result.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).Should().BeEmpty();

        return result.Results[0].GeneratedSources
            .ToDictionary(g => g.HintName, g => g.SourceText.ToString());
    }

    /// <summary>
    /// 生成器测试不应引用以下程序集，否则会触发 EF Core / Swagger 生成器或被 TestBase 中已实现的强类型 Id 污染发现结果。
    /// 这些程序集仅在对应测试里通过 <see cref="GetGeneratedCodeByHint"/> 的 <paramref name="extraAssemblyTypes"/> 显式引入。
    /// </summary>
    private static bool ShouldReferenceAssembly(Assembly assembly)
        => assembly.GetName().Name is not
            ("Len.StronglyTypedId.TestBase" or "Microsoft.EntityFrameworkCore" or "Swashbuckle.AspNetCore.SwaggerGen" or "Microsoft.OpenApi");

    #region EF Core 生成器（EfCoreCodeGenerator）

    [Theory]
    [InlineData("record struct")]
    [InlineData("record")]
    public void EfCore_Should_GenerateConverter_WhenReferencedAndConfigureConventions(string record)
    {
        var template = """
            using Microsoft.EntityFrameworkCore;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial {0} OrderId(Guid Value);

            public class TestDbContext : DbContext
            {{
                protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder) {{ }}
            }}
            """;
        var code = string.Format(template, record);

        var generated = GetGeneratedCodeByHint(code, typeof(Microsoft.EntityFrameworkCore.DbContext));

        generated.Should().ContainKey("Len.StronglyTypedId.OrderId.EntityFrameworkCore.g.cs");
        generated.Should().ContainKey("StronglyTypedIds.EntityFrameworkCore.g.cs");

        var converter = generated["Len.StronglyTypedId.OrderId.EntityFrameworkCore.g.cs"];
        converter.Should().Contain("class OrderIdConverter : global::Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<global::Len.StronglyTypedId.OrderId, Guid>");
        converter.Should().Contain("configurationBuilder.Properties<global::Len.StronglyTypedId.OrderId>().HaveConversion(typeof(OrderIdConverter));");

        generated["StronglyTypedIds.EntityFrameworkCore.g.cs"]
            .Should().Contain("OrderIdConverter.ApplyTo(configurationBuilder);");
    }

    [Fact]
    public void EfCore_Should_GenerateConverterForIntPrimitive()
    {
        var code = """
            using Microsoft.EntityFrameworkCore;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial record struct OrderId(int Value);

            public class TestDbContext : DbContext
            {
                protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder) { }
            }
            """;

        var generated = GetGeneratedCodeByHint(code, typeof(Microsoft.EntityFrameworkCore.DbContext));

        generated["Len.StronglyTypedId.OrderId.EntityFrameworkCore.g.cs"]
            .Should().Contain("ValueConverter<global::Len.StronglyTypedId.OrderId, int>");
    }

    [Fact]
    public void EfCore_Should_NotGenerate_WhenNoConfigureConventions()
    {
        var code = """
            using Microsoft.EntityFrameworkCore;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial record struct OrderId(Guid Value);
            """;

        var generated = GetGeneratedCodeByHint(code, typeof(Microsoft.EntityFrameworkCore.DbContext));

        generated.Keys.Should().NotContain(k => k.EndsWith(".EntityFrameworkCore.g.cs"));
    }

    /// <summary>
    /// 回归用例：不同命名空间下的同名强类型 Id 都生成进同一个 <c>StronglyTypedIds</c> 类，
    /// 转换器类名必须区分，否则相互冲突（CS0102 等）。
    /// </summary>
    /// <remarks>
    /// 只有确实出现同名时才给类名加命名空间前缀，无冲突场景下既有的 <c>OrderIdConverter</c>
    /// 命名保持不变（见上方 <c>EfCore_Should_GenerateConverter_WhenReferencedAndConfigureConventions</c>）。
    /// </remarks>
    [Fact]
    public void EfCore_Should_DisambiguateConverterNames_WhenSameNameInDifferentNamespaces()
    {
        var code = """
            using Len.StronglyTypedId;
            using Microsoft.EntityFrameworkCore;

            namespace Domain
            {
                [StronglyTypedId]
                public partial record struct OrderId(System.Guid Value);
            }

            namespace Contracts
            {
                [StronglyTypedId]
                public partial record struct OrderId(System.Guid Value);
            }

            namespace Host
            {
                public class TestDbContext : DbContext
                {
                    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder) { }
                }
            }
            """;

        var generated = GetGeneratedCodeByHint(code, typeof(Microsoft.EntityFrameworkCore.DbContext));

        generated["Domain.OrderId.EntityFrameworkCore.g.cs"]
            .Should().Contain("class Domain_OrderIdConverter :")
            .And.Contain("HaveConversion(typeof(Domain_OrderIdConverter))");

        generated["Contracts.OrderId.EntityFrameworkCore.g.cs"]
            .Should().Contain("class Contracts_OrderIdConverter :")
            .And.Contain("HaveConversion(typeof(Contracts_OrderIdConverter))");

        generated["StronglyTypedIds.EntityFrameworkCore.g.cs"]
            .Should().Contain("Domain_OrderIdConverter.ApplyTo(configurationBuilder);")
            .And.Contain("Contracts_OrderIdConverter.ApplyTo(configurationBuilder);");
    }

    #endregion

    #region Swagger 生成器（SwaggerCodeGenerator）

    [Theory]
    [InlineData("record struct")]
    [InlineData("record")]
    public void Swagger_Should_GenerateMapType_ForGuid(string record)
    {
        var code = $""""
            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial {record} OrderId(Guid Value);
            """";

        var generated = GetGeneratedCodeByHint(code, typeof(Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions));

        generated.Should().ContainKey("StronglyTypedIds.Swagger.g.cs");
        generated["StronglyTypedIds.Swagger.g.cs"]
            .Should().Contain("options.MapType<global::Len.StronglyTypedId.OrderId>(() => new global::Microsoft.OpenApi.Models.OpenApiSchema { Type = \"string\", Format = \"uuid\" });");
    }

    [Fact]
    public void Swagger_Should_GenerateMapType_ForInt()
    {
        var code = """
            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial record struct OrderId(int Value);
            """;

        var generated = GetGeneratedCodeByHint(code, typeof(Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions));

        generated["StronglyTypedIds.Swagger.g.cs"]
            .Should().Contain("options.MapType<global::Len.StronglyTypedId.OrderId>(() => new global::Microsoft.OpenApi.Models.OpenApiSchema { Type = \"integer\", Format = \"int32\" });");
    }

    [Fact]
    public void Swagger_Should_NotGenerate_WhenSwashbuckleNotReferenced()
    {
        var code = """
            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial record struct OrderId(Guid Value);
            """;

        var generated = GetGeneratedCodeByHint(code);

        generated.Keys.Should().NotContain("StronglyTypedIds.Swagger.g.cs");
    }

    #endregion

    #region 生成产物的可编译性（消费者未开启 ImplicitUsings）

    /// <summary>
    /// 回归用例：全部生成产物在「<c>ImplicitUsings=disable</c> 的消费者」里必须能编译。
    /// </summary>
    /// <remarks>
    /// <para>
    /// using 指令的作用域是文件级：合成编译的源码里虽有 <c>using System;</c>，但生成出来的每个文件
    /// 都得自带（或用全限定名写明）它依赖的每一个类型。这与
    /// <c>&lt;ImplicitUsings&gt;disable&lt;/ImplicitUsings&gt;</c>（且非 Web SDK）的消费者等价。
    /// </para>
    /// <para>
    /// 曾如此暴露过 Newtonsoft 产物里的裸 <c>Nullable</c>（<c>System.Nullable</c> 的短名）：开启
    /// ImplicitUsings 的消费者因为隐式 <c>global using System;</c> 而侥幸通过，关闭后即 CS0103。
    /// 断言放在此处而非某个具体生成器的测试里，是因为它守护的是全部生成器共有的契约。
    /// </para>
    /// </remarks>
    [Fact]
    public void GeneratedCode_Should_Compile_WithoutImplicitUsings()
    {
        var code = """
            using System;

            namespace Len.StronglyTypedId;

            [StronglyTypedId]
            public partial record OrderId(Guid Value);
            """;

        var compilation = CreateDefaultCompilation(code);

        // 显式传入取消令牌：生成 + Emit 是本套件里最重的两步，xUnit1051 要求的正是这个。
        var cancellationToken = TestContext.Current.CancellationToken;

        CSharpGeneratorDriver
            .Create(new StronglyTypedIdGenerator())
            .RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out _, cancellationToken);

        using var stream = new MemoryStream();
        var emit = outputCompilation.Emit(stream, cancellationToken: cancellationToken);

        var errors = emit.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).ToArray();

        errors.Should().BeEmpty(string.Join("\n", errors.Select(error => error.ToString())));
    }

    #endregion
}
